global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'auth_service'
    static_configs:
      - targets: ['auth_service:8001']

  - job_name: 'metrics_service'
    static_configs:
      - targets: ['metrics_service:8002']

  - job_name: 'ai_service'
    static_configs:
      - targets: ['ai_service:8003']

  - job_name: 'alert_service'
    static_configs:
      - targets: ['alert_service:8004']